apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitween-api
  labels:
    app.kubernetes.io/name: bitween-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitween-frontend
  labels:
    app.kubernetes.io/name: bitween-frontend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitween-postgres
  labels:
    app.kubernetes.io/name: bitween-postgres
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitween-rustfs
  labels:
    app.kubernetes.io/name: bitween-rustfs
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitween-migrations
  labels:
    app.kubernetes.io/name: bitween-migrations
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitween-worker
  labels:
    app.kubernetes.io/name: bitween-worker
automountServiceAccountToken: false
