apiVersion: openslo/v1
kind: SLO
metadata:
  name: bitween-frontend-availability
  labels:
    microservice: bitween-frontend
    sli: availability
    data_classes: internal
    pack: internal-korea
spec:
  service: bitween-frontend
  indicator:
    metadata:
      name: bitween-frontend-success-ratio
    spec:
      ratioMetric:
        counter: true
        good:
          metricSource:
            type: Prometheus
            spec:
              query: sum(rate(http_server_request_duration_seconds_count{service_name="bitween-frontend",http_response_status_code!~"5.."}[5m]))
        total:
          metricSource:
            type: Prometheus
            spec:
              query: sum(rate(http_server_request_duration_seconds_count{service_name="bitween-frontend"}[5m]))
  objectives:
    - displayName: Monthly successful shell request ratio
      target: 0.995
  timeWindow:
    - duration: 30d
      isRolling: true
  budgetingMethod: Occurrences
