"""
ui/theme_presets.py - 연한 색감 UI 테마 프리셋 (개인별 선택)
"""

from __future__ import annotations

from core.config import APP_CONFIG

_brand = APP_CONFIG.brand
_NAVY = _brand.primary_navy

# 각 프리셋: 표시 이름, 미리보기 색, COLORS 전체
THEME_PRESETS: dict[str, dict] = {
    "navy": {
        "label": "네이비 (기본)",
        "swatch": "#E0F4FD",
        "colors": {
            "bg": "#F1F5F9",
            "sidebar": "#E8F2FC",
            "sidebar_brand_bg": "#FFFFFF",
            "sidebar_surface": "#FFFFFF",
            "sidebar_border": "#B8D4EE",
            "sidebar_footer": "#5B7A9A",
            "nav_text": "#1E293B",
            "nav_hover": "#D6EBFF",
            "nav_active_bg": _NAVY,
            "nav_active_text": "#FFFFFF",
            "nav_accent": "#00A8E8",
            "card": "#FFFFFF",
            "accent": _NAVY,
            "accent_hover": "#163058",
            "accent_light": "#E0F4FD",
            "text": "#0F172A",
            "muted": "#64748B",
            "border": "#E2E8F0",
            "success": "#059669",
            "warn": "#D97706",
            "table_head": _NAVY,
            "table_head_fg": "#FFFFFF",
        },
    },
    "mint": {
        "label": "연한 초록",
        "swatch": "#BBF7D0",
        "colors": {
            "bg": "#F0FDF4",
            "sidebar": "#FFFFFF",
            "sidebar_border": "#D1FAE5",
            "sidebar_footer": "#6B7280",
            "nav_text": "#374151",
            "nav_hover": "#ECFDF5",
            "nav_active_bg": "#10B981",
            "nav_active_text": "#FFFFFF",
            "nav_accent": "#34D399",
            "card": "#FFFFFF",
            "accent": "#059669",
            "accent_hover": "#047857",
            "accent_light": "#D1FAE5",
            "text": "#14532D",
            "muted": "#6B7280",
            "border": "#A7F3D0",
            "success": "#059669",
            "warn": "#D97706",
            "table_head": "#10B981",
            "table_head_fg": "#FFFFFF",
        },
    },
    "sky": {
        "label": "연한 하늘",
        "swatch": "#BAE6FD",
        "colors": {
            "bg": "#F0F9FF",
            "sidebar": "#FFFFFF",
            "sidebar_border": "#E0F2FE",
            "sidebar_footer": "#64748B",
            "nav_text": "#334155",
            "nav_hover": "#F0F9FF",
            "nav_active_bg": "#0284C7",
            "nav_active_text": "#FFFFFF",
            "nav_accent": "#38BDF8",
            "card": "#FFFFFF",
            "accent": "#0369A1",
            "accent_hover": "#075985",
            "accent_light": "#E0F2FE",
            "text": "#0C4A6E",
            "muted": "#64748B",
            "border": "#BAE6FD",
            "success": "#059669",
            "warn": "#D97706",
            "table_head": "#0EA5E9",
            "table_head_fg": "#FFFFFF",
        },
    },
    "lavender": {
        "label": "연한 라벤더",
        "swatch": "#DDD6FE",
        "colors": {
            "bg": "#FAF5FF",
            "sidebar": "#FFFFFF",
            "sidebar_border": "#EDE9FE",
            "sidebar_footer": "#6B7280",
            "nav_text": "#4B5563",
            "nav_hover": "#F5F3FF",
            "nav_active_bg": "#7C3AED",
            "nav_active_text": "#FFFFFF",
            "nav_accent": "#A78BFA",
            "card": "#FFFFFF",
            "accent": "#6D28D9",
            "accent_hover": "#5B21B6",
            "accent_light": "#EDE9FE",
            "text": "#4C1D95",
            "muted": "#6B7280",
            "border": "#DDD6FE",
            "success": "#059669",
            "warn": "#D97706",
            "table_head": "#8B5CF6",
            "table_head_fg": "#FFFFFF",
        },
    },
    "peach": {
        "label": "연한 피치",
        "swatch": "#FED7AA",
        "colors": {
            "bg": "#FFF7ED",
            "sidebar": "#FFFFFF",
            "sidebar_border": "#FFEDD5",
            "sidebar_footer": "#78716C",
            "nav_text": "#57534E",
            "nav_hover": "#FFF7ED",
            "nav_active_bg": "#EA580C",
            "nav_active_text": "#FFFFFF",
            "nav_accent": "#FB923C",
            "card": "#FFFFFF",
            "accent": "#C2410C",
            "accent_hover": "#9A3412",
            "accent_light": "#FFEDD5",
            "text": "#7C2D12",
            "muted": "#78716C",
            "border": "#FED7AA",
            "success": "#059669",
            "warn": "#D97706",
            "table_head": "#F97316",
            "table_head_fg": "#FFFFFF",
        },
    },
    "rose": {
        "label": "연한 로즈",
        "swatch": "#FECDD3",
        "colors": {
            "bg": "#FFF1F2",
            "sidebar": "#FFFFFF",
            "sidebar_border": "#FFE4E6",
            "sidebar_footer": "#6B7280",
            "nav_text": "#4B5563",
            "nav_hover": "#FFF1F2",
            "nav_active_bg": "#E11D48",
            "nav_active_text": "#FFFFFF",
            "nav_accent": "#FB7185",
            "card": "#FFFFFF",
            "accent": "#BE123C",
            "accent_hover": "#9F1239",
            "accent_light": "#FFE4E6",
            "text": "#881337",
            "muted": "#6B7280",
            "border": "#FECDD3",
            "success": "#059669",
            "warn": "#D97706",
            "table_head": "#F43F5E",
            "table_head_fg": "#FFFFFF",
        },
    },
    "sand": {
        "label": "연한 샌드",
        "swatch": "#FDE68A",
        "colors": {
            "bg": "#FFFBEB",
            "sidebar": "#FFFFFF",
            "sidebar_border": "#FEF3C7",
            "sidebar_footer": "#78716C",
            "nav_text": "#57534E",
            "nav_hover": "#FFFBEB",
            "nav_active_bg": "#B45309",
            "nav_active_text": "#FFFFFF",
            "nav_accent": "#FBBF24",
            "card": "#FFFFFF",
            "accent": "#92400E",
            "accent_hover": "#78350F",
            "accent_light": "#FEF3C7",
            "text": "#78350F",
            "muted": "#78716C",
            "border": "#FDE68A",
            "success": "#059669",
            "warn": "#D97706",
            "table_head": "#D97706",
            "table_head_fg": "#FFFFFF",
        },
    },
}

DEFAULT_THEME_ID = "navy"
PRESET_ORDER: tuple[str, ...] = ("navy", "mint", "sky", "lavender", "peach", "rose", "sand")
